### PR TITLE
matter_server_beta: initial commit

### PR DESCRIPTION
**Pull request by agners**
Add Matter Server add-on which deploys beta releases of the Python Matter Server.

### CODE REVIEW

**Comment by marcelveldt** [comment]
1) Can we remove the version history and just start with v4 beta ?
2) Can we add a note that this is the beta version of the matter server add-on which could have (in)compatability issues with the production version of HA, use at your own risk

**Comment by agners** [comment]
> 1. Can we remove the version history and just start with v4 beta ?

Yes. I think I mainly kept it to legitimize the version number :sweat_smile: 

What version number would you like to use?


>     2. Can we add a note that this is the beta version of the matter server add-on which could have (in)compatability issues with the production version of HA, use at your own risk

There is a note in the docs already. I can make it more explicit and add it to the readme as well.

**Comment by marcelveldt** [comment]
I would use the 4.0.0b0 version as it is expected that this add-on will always bump in front of the stable one ?

**Comment by marcelveldt** [comment]
Correction: 5.0.0b0 as the add-on is one version ahead of the server version

**Comment by agners** [comment]
> Correction: 5.0.0b0 as the add-on is one version ahead of the server version

The b is kinda a Python thing. I don't think we have such version numbers in add-ons.

Since beta will be in the add-on title, I'll go for 5.0.0.

**Pull request merged**
